### ISSUE TITLE
Syntax Highlighting 

### ISSUE THREAD

**Issue by CameronDevine** [rtc-book/vm-vagrant#2] opened 2022-01-24 22:09 UTC
For some reason syntax highlighting is virtually not present with this VM. Functions appear in bold and comments are in purple, but everything else is black.

**Comment by CameronDevine** [comment] 2022-01-24 22:20
I tried exporting the preferences from my old VM and importing them into the new VM, but that didn't help for some reason.

**Comment by ricopicone** [comment] 2022-01-25 09:15
I am seeing this, too. I'm not sure of the root cause of this, but when I re-generate a new VM, this seems to be fixed. I'll post here when the latest is available.

**Comment by ricopicone** [comment] 2022-01-27 03:31
Fixed in the latest release.

**Closed as completed** 2022-01-27 03:32 UTC
